version: '3.9'

services:
  database:
    image: postgres
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRAS_DB: ${DATABASE_NAME}
      POSTGRAS_USER: ${DATABASE_USER}
      POSTGRAS_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - cup_counter-network

  backend:
    image: cup_counter
    ports:
      - '8080:8080'
    environment:
      CUPCOUNTER_DB_USER:  ${DATABASE_USER}
      CUPCOUNTER_DB_PASSWORD:  ${DATABASE_PASSWORD}
      CUPCOUNTER_DB_NAME:  ${DATABASE_NAME}
      CUPCOUNTER_DB_HOST:  database:5433
    depends_on:
      - database
    networks:
      - cup_counter-network
networks:
    cup_counter-network:
      driver: bridge




