spring:
  application:
    name: cup-counter

  datasource:
    url: jdbc:postgresql://${STUDENTS_DB_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: create
    show-sql: true



#  datasource:
#    url: jdbc:mysql://localhost:3306/cup_counter
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver




