spring:
  application:
    name: cup-counter

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true


bot:
  name: ${BOT_NAME}
  key: ${BOT_TOKEN}
  owner: ${BOT_OWNER}




#  datasource:
#    url: jdbc:mysql://localhost:3306/cup_counter
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver




